on: push
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4

            - name: Run install
              run: make install

            - name: Run setup
              run: make setup

            - name: Run tests
              run: make test

            - name: Run linter
              run: make lint

            - name: "Hello from Hexlet!"
              uses: hexlet-components/hello-from-hexlet-action@release